BASE_URL = "https://www.way2automation.com"
BANKING_APP_PATH = "/angularjs-protractor/banking"
REGISTRATION_APP_PATH = "/angularjs-protractor/registeration"
COOKIES_PAGE_URL = "https://www.sql-ex.ru"
TABS_PAGE_URL = "/way2auto_jquery/frames-and-windows.php"
DROP_PAGE_URL = "/way2auto_jquery/droppable.php"
ALERT_PAGE_URL = "/way2auto_jquery/alert.php"
